package com.zexqm.rpgproject.rpg.skill;

public enum SkillCastResult {
    STARTED,
    UNKNOWN_SKILL,
    DEBUG_FORBIDDEN,
    INVALID_STATE,
    WRONG_CLASS,
    WRONG_SPECIALIZATION,
    WRONG_WEAPON,
    WRONG_RESOURCE,
    NOT_LEARNED,
    INSUFFICIENT_RESOURCE,
    MISSING_SKILL_LINK,
    COOLDOWN,
    INVALID_AIM,
    INVALID_TARGET
}
